# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cliff\Documents\Projects\trunk\02_python\ShearPinCalc\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WindowObject(object):
    def setupUi(self, WindowObject):
        WindowObject.setObjectName("WindowObject")
        WindowObject.resize(800, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WindowObject.sizePolicy().hasHeightForWidth())
        WindowObject.setSizePolicy(sizePolicy)
        WindowObject.setMinimumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(WindowObject)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.input_1 = QtWidgets.QLineEdit(self.centralWidget)
        self.input_1.setMinimumSize(QtCore.QSize(0, 25))
        self.input_1.setText("")
        self.input_1.setPlaceholderText("")
        self.input_1.setObjectName("input_1")
        self.horizontalLayout_7.addWidget(self.input_1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(550, 90))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 140))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 761, 62))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.input_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_2.setMinimumSize(QtCore.QSize(177, 25))
        self.input_2.setObjectName("input_2")
        self.horizontalLayout_9.addWidget(self.input_2)
        spacerItem3 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_9.addWidget(self.label_22)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_9.addWidget(self.lineEdit_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.input_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_3.setMinimumSize(QtCore.QSize(177, 25))
        self.input_3.setObjectName("input_3")
        self.horizontalLayout_10.addWidget(self.input_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setEnabled(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.input_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_4.setEnabled(True)
        self.input_4.setMinimumSize(QtCore.QSize(0, 25))
        self.input_4.setObjectName("input_4")
        self.horizontalLayout_10.addWidget(self.input_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 771, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.input_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_5.setMinimumSize(QtCore.QSize(177, 25))
        self.input_5.setObjectName("input_5")
        self.horizontalLayout_11.addWidget(self.input_5)
        spacerItem5 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setEnabled(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.input_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_6.setEnabled(True)
        self.input_6.setMinimumSize(QtCore.QSize(0, 25))
        self.input_6.setObjectName("input_6")
        self.horizontalLayout_11.addWidget(self.input_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.input_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_7.setMinimumSize(QtCore.QSize(177, 25))
        self.input_7.setObjectName("input_7")
        self.horizontalLayout_5.addWidget(self.input_7)
        spacerItem6 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setEnabled(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.input_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_8.setEnabled(True)
        self.input_8.setMinimumSize(QtCore.QSize(0, 25))
        self.input_8.setObjectName("input_8")
        self.horizontalLayout_5.addWidget(self.input_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.input_9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_9.setMinimumSize(QtCore.QSize(177, 25))
        self.input_9.setObjectName("input_9")
        self.horizontalLayout_6.addWidget(self.input_9)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setEnabled(True)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.input_10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_10.setEnabled(True)
        self.input_10.setMinimumSize(QtCore.QSize(0, 25))
        self.input_10.setObjectName("input_10")
        self.horizontalLayout_6.addWidget(self.input_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.input_11 = QtWidgets.QLineEdit(self.centralWidget)
        self.input_11.setMinimumSize(QtCore.QSize(0, 25))
        self.input_11.setObjectName("input_11")
        self.horizontalLayout.addWidget(self.input_11)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout.addWidget(self.lineEdit_13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.input_12 = QtWidgets.QLineEdit(self.centralWidget)
        self.input_12.setMinimumSize(QtCore.QSize(0, 25))
        self.input_12.setObjectName("input_12")
        self.horizontalLayout_2.addWidget(self.input_12)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.input_13 = QtWidgets.QLineEdit(self.centralWidget)
        self.input_13.setMinimumSize(QtCore.QSize(0, 25))
        self.input_13.setObjectName("input_13")
        self.horizontalLayout_3.addWidget(self.input_13)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_3.addWidget(self.lineEdit_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label_17 = QtWidgets.QLabel(self.centralWidget)
        self.label_17.setMinimumSize(QtCore.QSize(100, 10))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        spacerItem11 = QtWidgets.QSpacerItem(16777215, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_18 = QtWidgets.QLabel(self.centralWidget)
        self.label_18.setMinimumSize(QtCore.QSize(100, 10))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        spacerItem12 = QtWidgets.QSpacerItem(16777215, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setMinimumSize(QtCore.QSize(100, 10))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.output_1 = QtWidgets.QLineEdit(self.centralWidget)
        self.output_1.setMinimumSize(QtCore.QSize(100, 25))
        self.output_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_1.setObjectName("output_1")
        self.horizontalLayout_8.addWidget(self.output_1)
        spacerItem13 = QtWidgets.QSpacerItem(16777215, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.output_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.output_2.setMinimumSize(QtCore.QSize(100, 25))
        self.output_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_2.setObjectName("output_2")
        self.horizontalLayout_8.addWidget(self.output_2)
        spacerItem14 = QtWidgets.QSpacerItem(16777215, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.output_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.output_3.setMinimumSize(QtCore.QSize(100, 25))
        self.output_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_3.setObjectName("output_3")
        self.horizontalLayout_8.addWidget(self.output_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        WindowObject.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(WindowObject)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        WindowObject.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(WindowObject)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(WindowObject)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(WindowObject)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(WindowObject)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu_5.addAction(self.action_3)
        self.menu_5.addAction(self.action_4)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())

        self.retranslateUi(WindowObject)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WindowObject)

    def retranslateUi(self, WindowObject):
        _translate = QtCore.QCoreApplication.translate
        WindowObject.setWindowTitle(_translate("WindowObject", "剪切销计算"))
        self.label.setText(_translate("WindowObject", "井号"))
        self.label_5.setText(_translate("WindowObject", " 井液密度（g/cm3）"))
        self.label_22.setText(_translate("WindowObject", "起爆装置垂深（m）"))
        self.label_10.setText(_translate("WindowObject", "   安全加压（MPa）"))
        self.label_23.setText(_translate("WindowObject", "起爆装置垂深（m）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WindowObject", "YB压力起爆装置"))
        self.label_11.setText(_translate("WindowObject", "套管内液体密度（g/cm3）"))
        self.label_24.setText(_translate("WindowObject", "    测试阀垂深（m）"))
        self.label_3.setText(_translate("WindowObject", "油管内液体密度（g/cm3）"))
        self.label_20.setText(_translate("WindowObject", "油管内液体深度（m）"))
        self.label_4.setText(_translate("WindowObject", "        安全加压（MPa）"))
        self.label_21.setText(_translate("WindowObject", "  起爆装置垂深（m）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WindowObject", "YCE压差起爆装置"))
        self.label_12.setText(_translate("WindowObject", "单颗剪切值（MPa/颗）"))
        self.label_13.setText(_translate("WindowObject", "起爆装置垂深（m）"))
        self.label_6.setText(_translate("WindowObject", "          温度（℃）"))
        self.label_7.setText(_translate("WindowObject", "起爆装置垂深（m）"))
        self.label_8.setText(_translate("WindowObject", "     下降百分比（%）"))
        self.label_9.setText(_translate("WindowObject", "起爆装置垂深（m）"))
        self.label_17.setText(_translate("WindowObject", "剪数量值（颗）："))
        self.label_18.setText(_translate("WindowObject", "最大加压（MPa）："))
        self.label_19.setText(_translate("WindowObject", "最小加压（MPa）："))
        self.label_2.setText(_translate("WindowObject", "川南航天能源科技有线公司 http://wwww.cetc.oil.com"))
        self.menu.setTitle(_translate("WindowObject", "单位制"))
        self.menu_2.setTitle(_translate("WindowObject", "计算"))
        self.menu_3.setTitle(_translate("WindowObject", "输出"))
        self.menu_4.setTitle(_translate("WindowObject", "打印"))
        self.menu_5.setTitle(_translate("WindowObject", "帮助"))
        self.action.setText(_translate("WindowObject", "公制"))
        self.action_2.setText(_translate("WindowObject", "英制"))
        self.action_3.setText(_translate("WindowObject", "快捷键"))
        self.action_4.setText(_translate("WindowObject", "关于"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowObject = QtWidgets.QMainWindow()
    ui = Ui_WindowObject()
    ui.setupUi(WindowObject)
    WindowObject.show()
    sys.exit(app.exec_())

